FROM openjdk:8-jre-alpine

COPY ./build/libs/website-application.jar /root/website-application.jar

WORKDIR /root

EXPOSE 8080

CMD ["java", "-server", "-Xms4g", "-Xmx4g", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "website-application.jar"]
